### PR TITLE
[#56] Adding endpoint for main-navigation

### PR DESCRIPTION
**Pull request by shailee-m**
## Fixes

Fixes https://github.com/creativecommons/project_creativecommons.org/issues/56 by @brylie 

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

### CODE REVIEW

**Comment by brylie** [comment]
@MuluhGodson, here is @shailee-m's pull request adding an HTML endpoint for the main navigation menu. As you know, we have since used Vue to render the main navigation, which uses JSON by convention. So, the idea was that this pull request was superseded by the Vue component.

How might the HTML rendered menu be useful in the CC Global Menu web component?

**Comment by MuluhGodson** [comment]
> @MuluhGodson, here is @shailee-m's pull request adding an HTML endpoint for the main navigation menu. As you know, we have since used Vue to render the main navigation, which uses JSON by convention. So, the idea was that this pull request was superseded by the Vue component.
> 
> How might the HTML rendered menu be useful in the CC Global Menu web component?

The idea basically is to reduce the number of nested loops, since basically each level or sub-menu requires a loop of its own and maybe some sort of recursive function. I don't think this is very ideal. The most optimum solution will be one which will not require us to alter the CC Global Menu web component each time there's a modification on the Menus on WordPress. 

Currently the function which the API calls is found here [creativecommons/wp-theme-creativecommons.org/inc/filters.php#L14](https://github.com/creativecommons/wp-theme-creativecommons.org/blob/d25fc2a4fecc4157ea6d4873b2fcb706beab93f7/inc/filters.php#L14) and if I recall correctly we had to modify this function to be able to have the API return sub-menus. This means for the two-level sub-menus we currently have, we may have to further rewrite this function yet with another loop to add the level 2 sub-menus to the level 1 sub-menus which is all added to the top-level menus. On the CC Global side, we'll also have to add an extra loop for the level 2 sub-menus since we currently have just a loop for Top menus and their direct child-menus. 

I've been tinkering, replacing the above function with the WordPress function `wp_nav_menu` returns an HTML output.

```php
public static function get_header_menu() {
    $header_menu_items = wp_nav_menu(
      array(
        'theme_location'  => 'main-navigation',
        'depth'           => 0,
        'container'       => 'div',
        'container_class' => 'navbar-menu',
        'items_wrap'      => '<div id="%1$s" class="navbar-end">%3$s</div>',
        'menu_class'      => 'navbar-menu',
        'menu_id'         => 'primary-menu',
        'after'           => '</div>',
        'walker'          => new Navwalker(),
      )
    );
    return $header_menu_items;
  }
```
//// Results
image

With this output, on the Vue side, we can just have a simple `div` element with a `v-html` directive and have all the menus rendered without any loops.

**Comment by brylie** [comment]
I believe we should agree on a maximum menu depth as a convention for the main navigation menu.

**Comment by MuluhGodson** [comment]
I think a maximum depth of 3 should be good. It is the current menu structure as of now. 
 Here is an excerpt from the Menu structure: 
- Who We Are ==========> Level 1
- What We Do ==========> Level 1
    - Advocacy (program page template - content needed) ==============> Level 2
        - Open Policy (no website, page needs to be created) ============================> Level 3
        - [Open Education](https://creativecommons.org/about/program-areas/education-oer/)
        - [CC Global Summit](https://summit.creativecommons.org/) (website - external link)
        - [CC Global Network](https://network.creativecommons.org/) (website)
    - Innovation
        - [CC Open Source](https://opensource.creativecommons.org/) (website)
        - [CC License Chooser](https://chooser-beta.creativecommons.org/) (website) 
        - [CC Legal Database](https://legaldb.creativecommons.org/) (website)
    - Capacity Building
        - [CC Certificate](https://certificates.creativecommons.org/) (website)
        - [CC Global Network](https://network.creativecommons.org/) (website)
- Licenses and Tools =======> Level 1

**Pull request closed without merging**
