### PR TITLE
 Docker added mariadb functionality #74

### PR DESCRIPTION
**Pull request by alainseys**
Issue ID: #74 

## Description
This PR gives the developers the posibility to switch between mariadb and mysql 

## Technical details
In the .env.sample i have added a new variable named DATABASE depending on what is entered to this variable docker compose wil build the container (mysql or mariadb)

Before starting the container after using mysql you need to remove the data container first.
After removing the volume you need to rebuild the docker image ``docker-compose up --build -d ``

## Tests
Tested on: Mac os 11.4 (Big Sur)
I have tested the containers and i am able to connect to wordpress succesfully like you could do with mysql.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the *default* branch of the repository (`main` or `master`).
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by brylie** [comment]
@alainseys I'm testing this now. It's a really clever solution to allow developers to toggle between MySQL and MariaDB! :smiley: 

For what it's worth, I ran auto-formatting on the `docker-compose.yml` and pushed the "Lint" commit to this branch.

**Comment by brylie** [comment]
@alainseys, I do get one issue from wp-cli:

> cc-base-wp-cli | Error: Error establishing a database connection.

Are you seeing that issue as well?

For now, we can ignore the issue with composer conflicts since it has already been documented in issue #76

**Comment by brylie** [comment]
@alainseys on closer look, the cc-base-db image is also throwing some errors:

```
cc-base-db  | 2021-07-01 12:16:33 0 [Note] mysqld (mysqld 10.3.30-MariaDB-1:10.3.30+maria~focal) starting as process 1 ...
cc-base-db  | 2021-07-01 12:16:33 0 [Note] InnoDB: Using Linux native AIO
cc-base-db  | 2021-07-01 12:16:33 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
cc-base-db  | 2021-07-01 12:16:33 0 [Note] InnoDB: Uses event mutexes
cc-base-db  | 2021-07-01 12:16:33 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
cc-base-db  | 2021-07-01 12:16:33 0 [Note] InnoDB: Number of pools: 1
cc-base-db  | 2021-07-01 12:16:33 0 [Note] InnoDB: Using SSE2 crc32 instructions
cc-base-db  | 2021-07-01 12:16:33 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
cc-base-db  | 2021-07-01 12:16:33 0 [Note] InnoDB: Completed initialization of buffer pool
cc-base-db  | 2021-07-01 12:16:33 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
cc-base-db  | 2021-07-01 12:16:33 0 [ERROR] InnoDB: Invalid flags 0x4800 in ./ibdata1
cc-base-db  | 2021-07-01 12:16:33 0 [ERROR] InnoDB: Plugin initialization aborted with error Data structure corruption
cc-base-db  | 2021-07-01 12:16:33 0 [Note] InnoDB: Starting shutdown...
cc-base-db  | 2021-07-01 12:16:34 0 [ERROR] Plugin 'InnoDB' init function returned error.
cc-base-db  | 2021-07-01 12:16:34 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
cc-base-db  | 2021-07-01 12:16:34 0 [Note] Plugin 'FEEDBACK' is disabled.
cc-base-db  | 2021-07-01 12:16:34 0 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
cc-base-db  | 2021-07-01 12:16:34 0 [ERROR] Unknown/unsupported storage engine: InnoDB
cc-base-db  | 2021-07-01 12:16:34 0 [ERROR] Aborting
```

Subsequently, WordPress cannot connect to the database:

image

**Comment by brylie** [comment]
@alainseys since you indicated having no visible errors, is there something I am perhaps doing incorrectly?

I basically:

1. checked out your branch
2. ran `docker-compose up`

Perhaps I need to destroy/rebuild some old image(s)?

**Comment by alainseys** [comment]
> @alainseys is there something I am perhaps doing incorrectly?
> 
> I basically:
> 
> 1. checked out the `alainseys:mariadb_v01.07.2021.00` branch
> 2. ran `docker-compose up`
> 
> Perhaps I need to destroy/rebuild some old image(s)?

As mentioned in the pr you need to remove the mysql data container and rebuild

**Comment by alainseys** [comment]
> @alainseys is there something I am perhaps doing incorrectly?
> 
> I basically:
> 
> 1. checked out the `alainseys:mariadb_v01.07.2021.00` branch
> 2. ran `docker-compose up`
> 
> Perhaps I need to destroy/rebuild some old image(s)?

I just reproduced these steps if you have been using the mysql version you need to delete the development_db_data volume you can do this by running ``docker volum rm development_db_data``or delete the volume in the docker client.

then you can rebuild the containers ``docker-compose up --build ``

the only 2 errors remailing are in cc-base-wp-cli there is an error reported wp-config.php not found and in the composer containers but this is beacause of a other issue

**Comment by brylie** [comment]
@alainseys thanks for the clarification. I added your instructions to a `README.md` in the `development/` folder for future reference :smiley:

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
@all-contributors please add @alainseys for code, docs

**Pull request merged**
